### ISSUE TITLE
Populate submitErrors when server responds w/ errors

### ISSUE THREAD

**Issue by soosap** [mhssmnn/redux-form-saga#16]
I have the following worker saga:

```js
export function* authenticateUserAsync(action) {
  try {
    const response = yield call(
      axios.post, `${process.env.BACKEND_URL}/auth/login`, action.payload,
    );

    yield put(userAuthenticated(response.data));
  } catch (error) {
    const { response: { data } } = error;

    yield put(stopSubmit('loginForm', data));
    // yield put({ type: AUTH_USER_FAILURE });
  }
}
```

Following the example in the README, in the catch case I'd simply dispatch the *failure* action like so:
`yield put({ type: AUTH_USER_FAILURE });`

In my case, however, the catch case returns an error object that I want to consume and display to the user. More specifically I avoid dispatching `AUTH_USER_FAILURE` and instead dispatch `stopSubmit('loginForm', data)` action creator that ships w/ redux-form. Doing so populates **submitErrors** like so:
<img width="419" alt="screen shot 2016-12-28 at 3 01 00 pm" src="https://cloud.githubusercontent.com/assets/7187705/21524543/20fd3aee-cd17-11e6-8ae3-fd201d220baa.png">

This approach feels hacky though. The mental model of handling `AUTH_USER_REQUEST`, `AUTH_USER_SUCCESS` and `AUTH_USER_FAILURE` gets lost that way. Wouldn't it be nicer if we could populate **submitErrors** by simply calling `yield put({ type: AUTH_USER_FAILURE, payload: errorsObj })` ? Any thoughts on this or even suggestions how to best handle this? I think server-side validation is a quite widespread problem. How do other people handle this?

**Comment by afitiskin** [comment]
@soosap sorry for the late response. I think you are using `redux-form-saga` not in the way it was designed.

Preparation step. You have to run `redux-form-saga` middleware using `sagaMiddleware.run`:
```javascript
import { formActionSaga } from 'redux-form-saga';

// add imported formActionSaga to list of sagas to run
const sagas = [yourFirstSaga, yourOtherSaga, ..., formActionSaga];
sagas.forEach(sagaMiddleware.run);
```

Then, you need to create action creator:
```javascript
// in actions.js
import { createFormAction } from 'redux-form-saga';
export const authenticate = createFormAction('AUTH_USER');
```

After that, you have to use `authenticate` function as submit handler for your form:
```javascript
import { authenticate } from '../actions.js';

...

<form onSubmit={handleSubmit(authenticate)}>...</form>
```

Now, the saga time:
```javascript
import { authenticate } from '../actions.js';


function* authWatcherSaga() {
  yield takeEvery(authenticate.REQUEST, handleAuthentication);
}

function* handleAuthentication(action) {
  // copied from your code
  try {
    const response = yield call(axios.post, `${process.env.BACKEND_URL}/auth/login`, action.payload);

    // to finish form submission with success, use action.success helper:
    yield put(action.success(response.data));
  } catch (error) {
    const { response: { data } } = error;

    // to finish form submission with success, use action.failure helper:
    // we have to wrap it in SubmissionError from redux-form:
    yield put(action.failure(new SubmissionError(data)));
  }
}
```

Export and run `authWatcherSaga` to take every `authenticate.REQUEST` action and handle them with `handleAuthentication`.

That's it!

**Comment by srosset81** [comment]
Thanks for the clearing up.

> // to finish form submission with success, use action.success helper:
>  yield put(action.success(response.data));

Correct me if I'm wrong, but I believe there is no "success" function passed with the action object. But there is a helper function located, in the example, in authenticate.success() and authenticate.failure().

**Comment by afitiskin** [comment]
@srosset81 yep, my mistake, you're right!

**Comment by soosap** [comment]
Awesome! Thank you for the detailed explanations. It helped me quite a lot to sort this out. The library is fantastic... it allows me to write code that is so much more readable! (y)
