### ISSUE TITLE
About handling failure

### ISSUE THREAD

**Issue by anhldbk** [mhssmnn/redux-form-saga#19]
Hi guys,

In the following saga, I deliberately returned an error

```js
/**
 * Authentication saga
 */
export function *loginFlow () {
  while (true) {
    let request = yield take(LOGIN_REQUEST);
    let error = 'Invalid username or password';
    yield put(loginFailure(error));
  }
}
```

And my `redux-form`:

```js
const { handleSubmit, error, submitting } = this.props;
const onSubmit = handleSubmit(actions.formAction);
return (
  <div>
    <form className="ui large form" onSubmit={onSubmit}>
    // ...
    </form>
    { error &&
      (
        <div className="ui error message">
          <span>Login failed</span>
        </div>
      )
    }      
  </div>
)
```
I expected to see the error message of `Login failed` when the form's submitted. But what I've got is a Promise rejection:

![screenshot from 2017-04-19 15-57-23](https://cloud.githubusercontent.com/assets/3270746/25171725/f752e1da-2518-11e7-9891-ccb120353a68.png)

Would you please tell me how to handle rejections properly?

**Comment by anhldbk** [comment]
So I wonder if this is a suitable way of handling rejections?

```js
    const onSubmit = (event) => (
      handleSubmit(actions.formAction)(event)
      .then(
        (success) => {
          console.log('@@@@ success', success)
        },
        (failure) => {
          console.log('@@@@ failure', failure);
        }
      )
    );
```

**Comment by afitiskin** [comment]
I'm not sure, what is `loginFailure` in your `loginFlow` saga? 
Also, as I know, you have to return instance of `SubmissionError` from `redux-form` to  get proper error in your form (http://redux-form.com/6.6.3/examples/submitValidation/). Try to following:

```javascript
import { SubmissionError } from 'redux-form'

export function *loginFlow () {
  while (true) {
    let request = yield take(LOGIN_REQUEST);
    let error = new SubmissionError({ _error: 'Invalid username or password' });
    yield put(loginFailure(error));
  }
}
```

**Comment by anhldbk** [comment]
@afitiskin Thank you! My problem can be solved using `stopSubmit`.

**Comment by dandonahoe** [comment]
@afitiskin @anhldbk This has been really useful, but I have a question about `loginFailure`. What does that actually look like in your code? The examples just say '...' so I'm having a lot of trouble wrapping my head around what that contains. Any help would be great.

**Comment by afitiskin** [comment]
@dandonahoe proper usage is following:
1. Create action: `const submitForm = createFormAction('SUBMIT_FORM')`
2. Pass it to handleSubmit of your form: `<form onSubmit={handleSubmit(submitForm)}>`
3. Take `submitForm.REQUEST` action in your saga and handle it:
```javascript
function* formSubmitWatcherSaga() {
  yield takeEvery(submitForm.REQUEST, handleFormSubmitSaga);
}

function* handleFormSubmitSaga(action) {
  const values = action.payload; // values of your form, you can validate it on client side
  // or send it directly to the server
  // it's up to you what you do

  if (successful) {
    yield put(submitForm.success()); // dispatch success action
    // it will automatically resolves the promise given to redux-form
    // so redux form will finish submit with successful result
  } else {
    const error = new SubmissionError({
      field1: 'This field is required', // mark specific field as it has error
      _error: 'Failed! Please fill the form correctly and try again', // set global form error
    });
    yield put(submitForm.failure(error)); // dispatch failure action
    // pass error (instance of SubmissionError) to it
    // promise given to redux-form will be rejected with the error
    // so all wrong fields will be marked and form will get global error 
  }
}
```

**Comment by afitiskin** [comment]
@dandonahoe please take a look at https://github.com/afitiskin/redux-saga-actions (updated version of redux-form-saga, fully compatible with this version) and https://github.com/afitiskin/redux-saga-routines (reworked and improved idea of this module)

**Comment by dandonahoe** [comment]
@afitiskin Thanks, this is great.

**Comment by afitiskin** [comment]
Updated README as well
