### ISSUE TITLE
Use flux-standard-actions

### ISSUE THREAD

**Issue by clayne11** [mhssmnn/redux-form-saga#2]
I think the idea is great but this library should use [`flux-standard-actions`](https://github.com/acdlite/flux-standard-action) to be as compatible as possible with the `redux` ecosystem.

**Comment by gbirke** [comment]
It already has a dependency on `flux-standard-actions`, although they are used nowhere and I wonder why this dependency was included. 

From what I've seen in the code and through using the library, all generated actions are plain objects with an `action` and a `type` property. Can you specify in what way the library does not adhere to the `flux-standard-actions` standard?

**Comment by mhssmnn** [comment]
@clayne11 as far as I can tell this would just involve using the `isFSA` function?

**Comment by mhssmnn** [comment]
Fixed in v0.0.5. I've moved the dependency to devDependency and used the `isFSA` in the tests.
