### ISSUE TITLE
Deprecation warning with saga 0.15.x (all([...effects]) - parallel effects)

### ISSUE THREAD

**Issue by KrzysztofKarol** [mhssmnn/redux-form-saga#29]
With https://github.com/redux-saga/redux-saga/releases/tag/v0.15.0

> `all` effect - explicit effect for parallel effects, which is exactly what we had been supporting by accepting yielded arrays, so the latter is become deprecated now in favor of this explicitness which nicely maps to the `Promise.all` API. Please use this from now on

PR: https://github.com/mhssmnn/redux-form-saga/pull/25

**Comment by mhssmnn** [comment]
Closed in #25
