### ISSUE TITLE
reduxForm connection and submit function

### ISSUE THREAD

**Issue by oliverwatkins** [mhssmnn/redux-form-saga#37]
How is my reduxForm connect object supposed to look like in the form file?

```
export default reduxForm({
	form: 'myForm',
	onSubmit: ????
})(MyPage)
```

Shouldn't the reduxForm object recieve the login submit function? This does not seem to work for me.

**Comment by afitiskin** [comment]
There are 2 options:
1. You pass action created with `createFormAction` to `handleSubmit` inside the component, see [Usage in README file](https://github.com/mhssmnn/redux-form-saga#usage)
2. You pass action created with `crateFormAction` to `reduxForm` function as `onSubmit` prop. See[ redux-form documentation](https://redux-form.com/8.1.0/docs/api/reduxform.md/#-code-onsubmit-function-code-optional-):

> onSubmit: The function to call with the form data when the handleSubmit() is fired from within the form component. If you do not specify it as a prop here, you must pass it as a parameter to handleSubmit() inside your form component.
