### ISSUE TITLE
redux form 6.0.5

### ISSUE THREAD

**Issue by cj** [mhssmnn/redux-form-saga#6]
I'm seeing `@@redux-form-saga/PROMISE`, but it's never calling my registered 'FORM_REQUEST' saga.  The code I'm using is below.

https://gist.github.com/cj/011caad7dd167269ead9065e8a36ccae

Any help getting it working would be greatly appreciated!

**Comment by cj** [comment]
ok, so I got it to work, I have to do`spawn(formActionSaga)`.  There's a 5 seconds delay until my saga gets called which I find strange....

**Comment by jontelm** [comment]
@cj Did you find out what the problem was? I have the same problem..

**Comment by afitiskin** [comment]
@cj @jontelm see Preparation section of the README: https://github.com/mhssmnn/redux-form-saga#preparation to properly handle `@@redux-form-saga/PROMISE` action.

About the delay: may you give more information about the delay problem?

**Comment by jontelm** [comment]
This is what I do, I'm fore sure doing something wrong. The same as @cj "I'm seeing @@redux-form-saga/PROMISE, but it's never calling my registered 'FORM_REQUEST' saga."

```
const sagaMiddleware = createSagaMiddleware();

const finalCreateStore = compose(
  applyMiddleware(sagaMiddleware),
  reduxReactRouter({ createHistory }),
  window.devToolsExtension ? window.devToolsExtension() : f => f
)(createStore);

const store = finalCreateStore(reducer);
sagaMiddleware.run(rootSaga);

export default store;
```

```
export default function* rootSaga() {
  yield []
    .concat(userSagas)
    .concat(loginSagas)
    .concat(spawn(formActionSaga)); // If I do this with spawn it works
}
```

```
export default [
  fork(takeEvery, actions.loginFormAction.REQUEST, postLoginRequest),
];
```

**Comment by afitiskin** [comment]
I prefer to run `formActionSaga` directly using `sagaMiddleware.run` as it stated in Preparation section of the README:

```
import formActionSaga from 'redux-form-saga'; // imprort
const sagaMiddleware = createSagaMiddleware();

const finalCreateStore = compose(
  applyMiddleware(sagaMiddleware),
  reduxReactRouter({ createHistory }),
  window.devToolsExtension ? window.devToolsExtension() : f => f
)(createStore);

const store = finalCreateStore(reducer);
const sagas = [
  formActionSaga, // prepare
  rootSaga,
];
sagas.forEach((saga) => sagaMiddleware.run(saga)); // run

export default store;
```

**Comment by jontelm** [comment]
@afitiskin Thanks, works!
