### ISSUE TITLE
Saga should be non blocking / rearranged

### ISSUE THREAD

**Issue by jhogendorn** [mhssmnn/redux-form-saga#7]
The saga uses `yield put(request);` when it should probably follow http://yelouafi.github.io/redux-saga/docs/advanced/NonBlockingCalls.html and use a different arrangement with `fork`.

The consequence of this is that if the saga returns success/failure immediately without issuing any other yields, the promise never gets resolved because the race has not yet been set up. Potentially could also be fixed by putting the race first.

**Comment by afitiskin** [comment]
@jhogendorn I created a PR to solve the issue, could you please test it on your cases?

**Comment by jhogendorn** [comment]
Hey @afitiskin I'm super stoked you've done this, but i'm flat chat and havent gotten to this just yet. I'm hoping to get to it in the next day or so. I had a quick look at the code and it looks sane at first glance :)

**Comment by mhssmnn** [comment]
@jhogendorn this looks ok to me, if you're ok with it I'll merge

**Comment by afitiskin** [comment]
Updated PR, now code is backward-compatible. Also I used `yield [...]` instead of `fork` to make code more simple with same result
